name: latest

on:
  push:
    paths:
      - Dockerfile

  workflow_dispatch:

env:
  DOCKER_BASE_NAME: slashnephy/tpruvot-ccminer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: ${{ env.DOCKER_BASE_NAME }}:latest
          cache-from: ${{ env.DOCKER_BASE_NAME }}:latest
          build-args: BUILDKIT_INLINE_CACHE=1
